#!/bin/bash

echo $"This script will download and start the latest knoppix-installer to your home directory. Do you want to proceed?"" [Y/n]"
read answer
[ "$answer" = "n" -o "$answer" = "N" ] && exit 1
FILE=$(wget http://debian.tu-bs.de/knoppix/installer/latest -O -)
echo "Downloading $FILE ..."
cd $HOME
wget http://debian.tu-bs.de/knoppix/installer/$FILE
tar xzf $FILE
cd knx-installer-*
sudo chown -R root:root .
sudo ./knoppix-installer
